---
# Bosh DNS Aliases
- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases
  value:
  - domain: uaa.((paasta_domain))
    targets:
    - query: '*'
      instance_group: haproxy
      deployment: ((paasta_deployment_name))
      network: ((paasta_public_haproxy_network_name))
      domain: bosh
  - domain: api.((paasta_domain))
    targets:
    - query: '*'
      instance_group: haproxy
      deployment: ((paasta_deployment_name))
      network: ((paasta_public_haproxy_network_name))
      domain: bosh
  - domain: login.((paasta_domain))
    targets:
    - query: '*'
      instance_group: haproxy
      deployment: ((paasta_deployment_name))
      network: ((paasta_public_haproxy_network_name))
      domain: bosh
  - domain: sql-db.service.cf.internal
    targets:
    - query: '*'
      instance_group: database
      deployment: ((paasta_deployment_name))
      network: ((paasta_network_name))
      domain: bosh
  - domain: eureka.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-registration
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: haproxy.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-haproxy
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: cf.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-api
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: common.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-common-api
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: log.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-log-api
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: zuul.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-gateway
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: storage.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-storage-api
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
  - domain: swift.service.portalapi.internal
    targets:
    - query: '*'
      instance_group: paas-ta-portal-binary_storage
      deployment: paasta-portal-api
      network: ((internal_networks_name))
      domain: bosh
